const fs = require('fs');

function HelloWorldPlugin(options) {
    // 使用配置（options）设置插件实例
    console.log(arguments);
}

HelloWorldPlugin.prototype.apply = function(compiler) {
    compiler.plugin('emit', function(compilation, callback){
        // 回掉函数有两个参数
        // compilation和下一个回调函数，callback可以不传
        // 同步事件不传callback
        compilation.chunks.forEach(function(chunk){
            console.log('chunk.name', chunk.name);
            console.log('=====================================');
            chunk.modules.forEach(function(module){
                // console.log('module', module.resource);
                if(module&&module.resource&&(module.resource.indexOf('menu.js')>=0)){
                    // compilation.assets['menu.js']=module._cachedSource.source
                    // console.log(module)
                    module.fileDependencies.forEach(function(filepath){
                        console.log('filepath', filepath);
                        let menu=fs.readFileSync(filepath).toString();
                        let variable=menu.match(/import [a-zA-Z{}, *]+/g);
                        if(variable&&variable.length){
                            let reg=variable.map(function(val){
                                return val.replace(',','|').replace(/import|from|\{|\}|as|\*| /g,'');
                            });
                            menu=menu.replace(/(import.+)|(\/\/.*)|(\/\*.*\*\/)|(export default)|(vue.*)/g,'');
                            if(reg&&reg.length){
                                reg=new RegExp(reg.join('|'),'g');
                                menu=menu.replace(reg,'""').replace(/""""/g,'""');
                            }
                        }
                        menu=JSON.stringify(eval(menu),null,'  ');
                        compilation.assets['menu.json'] = {
                            source: () => {
                                return menu
                            },
                            size: () => {
                                return menu.length
                            }
                        };
                    });
                }

            });
        });
        // 最后调用callback
        callback();
    });
};
module.exports = HelloWorldPlugin;

/*
{
    dependencies:
        [ ConstDependency { module: null, expression: '', range: [Array], loc: [Object] },
            CommonJsRequireDependency {
            module: [Object],
            request: '@project/frame',
            userRequest: '@project/frame',
            range: [Array],
            loc: [Object],
            optional: false,
            __NormalModuleFactoryCache: [Object] },
            RequireHeaderDependency { module: null, range: [Array], loc: [Object] },
            RequireHeaderDependency { module: null, range: [Array], loc: [Object] },
            CommonJsRequireDependency {
            module: [Object],
            request: './module',
            userRequest: './module',
            range: [Array],
            loc: [Object],
            optional: false,
            __NormalModuleFactoryCache: [Object] },
            RequireHeaderDependency { module: null, range: [Array], loc: [Object] },
            CommonJsRequireDependency {
            module: [Object],
            request: '../custom/amp/monitorAlarm/alarmOverview/alarmOverview.vue',
            userRequest: '../custom/amp/monitorAlarm/alarmOverview/alarmOverview.vue',
            range: [Array],
            loc: [Object],
            optional: false,
            __NormalModuleFactoryCache: [Object] },
            CommonJsRequireDependency {
            module: [Object],
            request: '../custom/amp/monitorAlarm/homeIndex/mangerHome.vue',
            userRequest: '../custom/amp/monitorAlarm/homeIndex/mangerHome.vue',
            range: [Array],
            loc: [Object],
            optional: false,
            __NormalModuleFactoryCache: [Object] },
            RequireHeaderDependency { module: null, range: [Array], loc: [Object] },
            RequireHeaderDependency { module: null, range: [Array], loc: [Object] },
            CommonJsRequireDependency {
            module: [Object],
            request: '../custom/amp/monitorAlarm/alarmEventStage/alarmEventStageListSettings.js',
            userRequest: '../custom/amp/monitorAlarm/alarmEventStage/alarmEventStageListSettings.js',
            range: [Array],
            loc: [Object],
            optional: false,
            __NormalModuleFactoryCache: [Object] },
            RequireHeaderDependency { module: null, range: [Array], loc: [Object] },
            CommonJsRequireDependency {
            module: [Object],
            request: '../custom/amp/addNew/triggerPrototype/table',
            userRequest: '../custom/amp/addNew/triggerPrototype/table',
            range: [Array],
            loc: [Object],
            optional: false,
            __NormalModuleFactoryCache: [Object] },
            CommonJsRequireDependency {
            module: [Object],
            request: '../custom/amp/addNew/monitoringPrototypeItem/table',
            userRequest: '../custom/amp/addNew/monitoringPrototypeItem/table',
            range: [Array],
            loc: [Object],
            optional: false,
            __NormalModuleFactoryCache: [Object] },
            RequireHeaderDependency { module: null, range: [Array], loc: [Object] },
            CommonJsRequireDependency {
            module: [Object],
            request: '../custom/amp/addNew/hostPrototype/table',
            userRequest: '../custom/amp/addNew/hostPrototype/table',
            range: [Array],
            loc: [Object],
            optional: false,
            __NormalModuleFactoryCache: [Object] },
            RequireHeaderDependency { module: null, range: [Array], loc: [Object] },
            CommonJsRequireDependency {
            module: [Object],
            request: '../custom/amp/addNew/monitoringDiscoveryItem/table',
            userRequest: '../custom/amp/addNew/monitoringDiscoveryItem/table',
            range: [Array],
            loc: [Object],
            optional: false,
            __NormalModuleFactoryCache: [Object] },
            RequireHeaderDependency { module: null, range: [Array], loc: [Object] },
            CommonJsRequireDependency {
            module: [Object],
            request: '../custom/amp/addNew/triggersManage/table',
            userRequest: '../custom/amp/addNew/triggersManage/table',
            range: [Array],
            loc: [Object],
            optional: false,
            __NormalModuleFactoryCache: [Object] },
            RequireHeaderDependency { module: null, range: [Array], loc: [Object] },
            CommonJsRequireDependency {
            module: [Object],
            request: '../custom/amp/addNew/monitoringItem/table',
            userRequest: '../custom/amp/addNew/monitoringItem/table',
            range: [Array],
            loc: [Object],
            optional: false,
            __NormalModuleFactoryCache: [Object] },
            RequireHeaderDependency { module: null, range: [Array], loc: [Object] },
            CommonJsRequireDependency {
            module: [Object],
            request: '../custom/amp/addNew/monitoringSet/table',
            userRequest: '../custom/amp/addNew/monitoringSet/table',
            range: [Array],
            loc: [Object],
            optional: false,
            __NormalModuleFactoryCache: [Object] },
            RequireHeaderDependency { module: null, range: [Array], loc: [Object] },
            CommonJsRequireDependency {
            module: [Object],
            request: '../custom/amp/relay/hostTemplate.vue',
            userRequest: '../custom/amp/relay/hostTemplate.vue',
            range: [Array],
            loc: [Object],
            optional: false,
            __NormalModuleFactoryCache: [Object] },
            RequireHeaderDependency { module: null, range: [Array], loc: [Object] },
            CommonJsRequireDependency {
            module: [Object],
            request: '../components/pageCustom/table.js',
            userRequest: '../components/pageCustom/table.js',
            range: [Array],
            loc: [Object],
            optional: false,
            __NormalModuleFactoryCache: [Object] },
            RequireHeaderDependency { module: null, range: [Array], loc: [Object] },
            CommonJsRequireDependency {
            module: [Object],
            request: '../components/pageCustom/render.vue',
            userRequest: '../components/pageCustom/render.vue',
            range: [Array],
            loc: [Object],
            optional: false,
            __NormalModuleFactoryCache: [Object] },
            RequireHeaderDependency { module: null, range: [Array], loc: [Object] },
            CommonJsRequireDependency {
            module: [Object],
            request: '../custom/amp/addNew/targetManage/targetManagePage.js',
            userRequest: '../custom/amp/addNew/targetManage/targetManagePage.js',
            range: [Array],
            loc: [Object],
            optional: false,
            __NormalModuleFactoryCache: [Object] },
            RequireHeaderDependency { module: null, range: [Array], loc: [Object] },
            CommonJsRequireDependency {
            module: [Object],
            request: '../custom/amp/monitorAlarm/comAnalysis/comAnalysis/comAnalysisWrap.vue',
            userRequest: '../custom/amp/monitorAlarm/comAnalysis/comAnalysis/comAnalysisWrap.vue',
            range: [Array],
            loc: [Object],
            optional: false,
            __NormalModuleFactoryCache: [Object] },
            RequireHeaderDependency { module: null, range: [Array], loc: [Object] },
            CommonJsRequireDependency {
            module: [Object],
            request: '../components/focusTopo/main.vue',
            userRequest: '../components/focusTopo/main.vue',
            range: [Array],
            loc: [Object],
            optional: false,
            __NormalModuleFactoryCache: [Object] },
            RequireHeaderDependency { module: null, range: [Array], loc: [Object] } ],
            blocks: [],
    variables: [],
    context: 'C:\\app\\web_amp\\src\\data',
    reasons: [ ModuleReason { module: [Object], dependency: [Object] } ],
    debugId: 1014,
    lastId: null,
    id: './src/data/menu.js',
    portableId: 'node_modules/babel-loader/lib/index.js!src/data/menu.js',
    index: 607,
    index2: 1626,
    depth: 2,
    used: true,
    usedExports: true,
    providedExports: true,
    chunks:
    [ Chunk {
        id: 0,
        ids: [Array],
        debugId: 1001,
        name: 'app',
        modules: [Array],
        entrypoints: [Array],
        chunks: [],
        parents: [],
        blocks: [],
        origins: [Array],
        files: [Array],
        rendered: true,
        entryModule: [Object],
        __OccurenceOrderPlugin_occursInEntry: undefined,
        hash: '27e88798dd062e5fdb92d345fa09692f',
        renderedHash: '27e88798dd062e5fdb92' } ],
        warnings: [],
    dependenciesWarnings: [],
    errors: [],
    dependenciesErrors: [],
    strict: true,
    meta: {},
    request: 'C:\\app\\web_amp\\node_modules\\babel-loader\\lib\\index.js!C:\\app\\web_amp\\src\\data\\menu.js',
        userRequest: 'C:\\app\\web_amp\\src\\data\\menu.js',
    rawRequest: './data/menu',
    parser:
    Parser {
    _plugins:
    { 'evaluate Literal': [Array],
        'evaluate LogicalExpression': [Array],
        'evaluate BinaryExpression': [Array],
        'evaluate UnaryExpression': [Array],
        'evaluate typeof undefined': [Array],
        'evaluate Identifier': [Array],
        'evaluate MemberExpression': [Array],
        'evaluate CallExpression': [Array],
        'evaluate CallExpression .replace': [Array],
        'evaluate CallExpression .substr': [Array],
        'evaluate TemplateLiteral': [Array],
        'evaluate TaggedTemplateExpression': [Array],
        'evaluate CallExpression .substring': [Array],
        'evaluate CallExpression .split': [Array],
        'evaluate ConditionalExpression': [Array],
        'evaluate ArrayExpression': [Array],
        'can-rename process': [Array],
        'can-rename process.env': [Array],
        'can-rename process.env.NODE_ENV': [Array],
        'evaluate Identifier process.env.NODE_ENV': [Array],
        'expression process.env.NODE_ENV': [Array],
        'evaluate typeof process.env.NODE_ENV': [Array],
        'typeof process.env.NODE_ENV': [Array],
        'expression __webpack_hash__': [Array],
        'evaluate typeof __webpack_hash__': [Array],
        'evaluate Identifier module.hot': [Array],
        'call module.hot.accept': [Array],
        'call module.hot.decline': [Array],
        'expression module.hot': [Array],
        'expression global': [Array],
        'expression process': [Array],
        'expression Buffer': [Array],
        'expression setImmediate': [Array],
        'expression clearImmediate': [Array],
        'call require': [Array],
        program: [Array],
        'evaluate typeof define': [Array],
        'typeof define': [Array],
        'evaluate define': [Array],
        'expression define': [Array],
        'call define': [Array],
        'evaluate typeof exports': [Array],
        'typeof exports': [Array],
        'evaluate exports': [Array],
        'expression exports': [Array],
        'call exports': [Array],
    import: [Array],
        'import specifier': [Array],
        'expression imported var': [Array],
        'expression imported var.*': [Array],
        'call imported var': [Array],
        'hot accept callback': [Array],
        'hot accept without callback': [Array],
    export: [Array],
        'export import': [Array],
        'export expression': [Array],
        'export declaration': [Array],
        'export specifier': [Array],
        'export import specifier': [Array],
        'call require:amd:array': [Array],
        'call require:amd:item': [Array],
        'call require:amd:context': [Array],
        'call define:amd:array': [Array],
        'call define:amd:item': [Array],
        'call define:amd:context': [Array],
        'expression require.amd': [Array],
        'expression define.amd': [Array],
        'expression __webpack_amd_options__': [Array],
        'evaluate typeof define.amd': [Array],
        'evaluate typeof require.amd': [Array],
        'evaluate Identifier define.amd': [Array],
        'evaluate Identifier require.amd': [Array],
        'can-rename define': [Array],
        'rename define': [Array],
        'typeof require': [Array],
        'evaluate typeof require': [Array],
        'typeof require.resolve': [Array],
        'evaluate typeof require.resolve': [Array],
        'typeof require.resolveWeak': [Array],
        'evaluate typeof require.resolveWeak': [Array],
        'evaluate typeof module': [Array],
        'assign require': [Array],
        'can-rename require': [Array],
        'rename require': [Array],
        'typeof module': [Array],
        'expression require.cache': [Array],
        'expression require': [Array],
        'call require:commonjs:item': [Array],
        'call require:commonjs:context': [Array],
        'call require.resolve': [Array],
        'call require.resolveWeak': [Array],
        'call require.resolve(Weak)': [Array],
        'call require.resolve(Weak):item': [Array],
        'call require.resolve(Weak):context': [Array],
        'expression __filename': [Array],
        'evaluate Identifier __filename': [Array],
        'expression __dirname': [Array],
        'evaluate Identifier __dirname': [Array],
        'expression require.main': [Array],
        'expression require.extensions': [Array],
        'expression module.loaded': [Array],
        'expression module.id': [Array],
        'expression module.exports': [Array],
        'expression module': [Array],
        'call require.config': [Array],
        'call requirejs.config': [Array],
        'expression require.version': [Array],
        'expression requirejs.onError': [Array],
        'expression __webpack_require__': [Array],
        'evaluate typeof __webpack_require__': [Array],
        'expression __webpack_public_path__': [Array],
        'evaluate typeof __webpack_public_path__': [Array],
        'expression __webpack_modules__': [Array],
        'evaluate typeof __webpack_modules__': [Array],
        'expression __webpack_chunk_load__': [Array],
        'evaluate typeof __webpack_chunk_load__': [Array],
        'expression __non_webpack_require__': [Array],
        'evaluate typeof __non_webpack_require__': [Array],
        'expression __webpack_nonce__': [Array],
        'evaluate typeof __webpack_nonce__': [Array],
        'expression require.onError': [Array],
        'evaluate typeof require.onError': [Array],
        'statement if': [Array],
        'expression ?:': [Array],
        'evaluate Identifier __resourceQuery': [Array],
        'expression __resourceQuery': [Array],
        'call require.include': [Array],
        'evaluate typeof require.include': [Array],
        'typeof require.include': [Array],
        'call require.ensure': [Array],
        'evaluate typeof require.ensure': [Array],
        'typeof require.ensure': [Array],
        'call require.context': [Array],
        'call System.import': [Array],
        'import-call': [Array],
        'typeof System.import': [Array],
        'evaluate typeof System.import': [Array],
        'typeof System': [Array],
        'evaluate typeof System': [Array],
        'evaluate typeof System.set': [Array],
        'expression System.set': [Array],
        'evaluate typeof System.get': [Array],
        'expression System.get': [Array],
        'evaluate typeof System.register': [Array],
        'expression System.register': [Array],
        'expression System': [Array] },
    options: undefined,
        scope: undefined,
        state: undefined,
        comments: undefined },
    resource: 'C:\\app\\web_amp\\src\\data\\menu.js',
        loaders: [ { loader: 'C:\\app\\web_amp\\node_modules\\babel-loader\\lib\\index.js' } ],
    fileDependencies: [ 'C:\\app\\web_amp\\src\\data\\menu.js' ],
    contextDependencies: [],
    error: null,
    _source:
    SourceMapSource {
    _value: '\'use strict\';\n\nObject.defineProperty(exports, "__esModule", {\n    value: true\n});\n\nvar _frame = require(\'@project/frame\');\n\nvar _module = require(\'./module\');\n\nvar _module2 = _interopRequireDefault(_module);\n\nvar _alarmOverview = require(\'../custom/amp/monitorAlarm/alarmOverview/alarmOverview.vue\');\n\nvar _alarmOverview2 = _interopRequireDefault(_alarmOverview);\n\nvar _mangerHome = require(\'../custom/amp/monitorAlarm/homeIndex/mangerHome.vue\');\n\nvar _mangerHome2 = _interopRequireDefault(_mangerHome);\n\nvar _alarmEventStageListSettings = require(\'../custom/amp/monitorAlarm/alarmEventStage/alarmEventStageListSettings.js\');\n\nvar _table = require(\'../custom/amp/addNew/triggerPrototype/table\');\n\nvar _table2 = _interopRequireDefault(_table);\n\nvar _table3 = require(\'../custom/amp/addNew/monitoringPrototypeItem/table\');\n\nvar _table4 = _interopRequireDefault(_table3);\n\nvar _table5 = require(\'../custom/amp/addNew/hostPrototype/table\');\n\nvar _table6 = _interopRequireDefault(_table5);\n\nvar _table7 = require(\'../custom/amp/addNew/monitoringDiscoveryItem/table\');\n\nvar _table8 = _interopRequireDefault(_table7);\n\nvar _table9 = require(\'../custom/amp/addNew/triggersManage/table\');\n\nvar _table10 = _interopRequireDefault(_table9);\n\nvar _table11 = require(\'../custom/amp/addNew/monitoringItem/table\');\n\nvar _table12 = _interopRequireDefault(_table11);\n\nvar _table13 = require(\'../custom/amp/addNew/monitoringSet/table\');\n\nvar _table14 = _interopRequireDefault(_table13);\n\nvar _hostTemplate = require(\'../custom/amp/relay/hostTemplate.vue\');\n\nvar _hostTemplate2 = _interopRequireDefault(_hostTemplate);\n\nvar _table15 = require(\'../components/pageCustom/table.js\');\n\nvar _table16 = _interopRequireDefault(_table15);\n\nvar _render = require(\'../components/pageCustom/render.vue\');\n\nvar _render2 = _interopRequireDefault(_render);\n\nvar _targetManagePage = require(\'../custom/amp/addNew/targetManage/targetManagePage.js\');\n\nvar _targetManagePage2 = _interopRequireDefault(_targetManagePage);\n\nvar _comAnalysisWrap = require(\'../custom/amp/monitorAlarm/comAnalysis/comAnalysis/comAnalysisWrap.vue\');\n\nvar _comAnalysisWrap2 = _interopRequireDefault(_comAnalysisWrap);\n\nvar _main = require(\'../components/focusTopo/main.vue\');\n\nvar _main2 = _interopRequireDefault(_main);\n\nfunction _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }\n\nexports.default = [{\n    "name": "首页",\n    authorityCode: \'AMP-MONITOR-INDEX-MENU\',\n    "path": "snc-amp_monitor_manger_home",\n    vue: _render2.default,\n    data: { option: { type: \'home\' } }\n}, {\n    "name": "监控告警",\n    authorityCode: \'AMP-MONITOR-MENU\',\n    "path": "snc-amp_monitor_manger",\n\n    navMenuIcon: \'iconfont icon-jiankonggaojing\',\n\n    isShowInNavMenu: true,\n    "children": [{\n        "name": "告警总览",\n        authorityCode: \'AMP-MONITOR-All-ALERT-MENU\',\n        "path": "snc-amp_alarm_overview",\n        icon: \'iconfont icon-gaojingxiangqing\',\n        vue: _alarmOverview2.default\n    }, {\n        "name": "实时监控",\n        authorityCode: \'AMP-MONITOR-THIS-TIME-ALERT-MENU\',\n        "path": "snc-amp_monitor_manger_index",\n        icon: \'iconfont icon-jiankong\',\n        vue: _mangerHome2.default,\n        data: [{\n            name: \'告警事件台\',\n            authorityCode: \'AMP-MONITOR-ALARM-EVENT-TABLE-MENU\',\n            data: _alarmEventStageListSettings.pendingListSettings\n        }]\n    }, {\n        "name": "对比分析",\n        authorityCode: \'AMP-MONITOR-ALERT-MENU\',\n        "path": "snc-amp_monitor_analysis",\n        icon: \'iconfont icon-chartarea\',\n        vue: _comAnalysisWrap2.default,\n        data: {}\n    }, {\n        "name": "配置管理",\n        authorityCode: \'AMP-MONITOR-CONFIG-MENU\',\n        icon: \'iconfont icon-xitongpeizhi\',\n        "children": [{\n            "name": "代理主机配置",\n            authorityCode: \'AMP-MONITOR-CONFIG-PROXY-MENU\',\n            "path": "snc-amp_dev_mange_index",\n            vue: _frame.ModuleRender,\n            data: _module2.default.proxyHostManagementList\n        }, {\n            "name": "告警扣分配置",\n            authorityCode: \'AMP-MONITOR-CONFIG-ALERT-MENU\',\n            "path": "alarm_priority_config",\n            vue: _frame.ModuleRender,\n            data: _module2.default.alarmDeductionRules\n        }, {\n            "name": "模板配置",\n            authorityCode: \'AMP-MONITOR-CONFIG-HOST-HOST-MENU\',\n            "path": "alarm_template_manger",\n            vue: _hostTemplate2.default,\n            data: [{\n                name: \'模板配置\',\n                authorityCode: \'AMP-MONITOR-CONFIG-HOST-HOST-TWO-MENU\',\n                data: _module2.default.templateManagement\n            }]\n        }, {\n            "name": "监控配置",\n            authorityCode: \'AMP-MONITOR-CONFIG-HOST-MENU\',\n            "path": "alarm_host_list",\n            vue: _hostTemplate2.default,\n            data: [{\n                name: \'监控配置\',\n                authorityCode: \'AMP-MONITOR-CONFIG-HOST-TWO-MENU\',\n                data: _module2.default.resourceManagement\n            }, {\n                name: \'自发现规则管理\',\n                authorityCode: \'AMP-MONITOR-CONFIG-TEMPLATE-DISCOVER-MENU\',\n                data: _table8.default\n            }, {\n                name: \'监控项原型管理\',\n                authorityCode: \'AMP-CONFIG-TEMPLATE-MORNITORHOSTPROTOTYPE-MENU\',\n                data: _table4.default\n            }, {\n                name: \'主机原型管理\',\n                authorityCode: \'AMP-CONFIG-TEMPLATE-HOSTPROTOTYPE-MENU\',\n                data: _table6.default\n            }, {\n                name: \'触发器原型管理\',\n                authorityCode: \'AMP-CONFIG-TEMPLATE-TRIGGERHOSTPROTOTYPE-MENU\',\n                data: _table2.default\n            }, {\n                name: \'触发器\',\n                authorityCode: \'AMP-CONFIG-TEMPLATE-TRIGGER-MENU\',\n                data: _table10.default\n            }, {\n                name: \'监控项\',\n                authorityCode: \'AMP-MONITOR-CONFIG-TEMPLATE-MONITORITEM-MENU\',\n                data: _table12.default\n            }, {\n                name: \'监控集\',\n                authorityCode: \'AMP-CONFIG-TEMPLATE-APPLICATION-MENU\',\n                data: _table14.default\n            }]\n        }, {\n            "name": "动作配置",\n            authorityCode: \'AMP-MONITOR-CONFIG-ACTION-MENU\',\n            "path": "actionManageList",\n            vue: _frame.ModuleRender,\n            data: _module2.default.actionManagement\n        }]\n    }, {\n        name: \'基础配置\',\n        path: \'basicConfiguration\',\n        position: \'bottom\',\n        authorityCode: \'AMP-BASIC-CONFIGURATION-MENU\',\n        vue: _frame.TabsRender,\n        icon: \'iconfont icon-xitongpeizhi\',\n        data: [{\n            "name": "仪表盘",\n            authorityCode: \'AMP-PAGECUSTOM-MENU\',\n            vue: _frame.ModuleRender,\n            data: _table16.default\n        }, {\n            name: \'指标配置\',\n            authorityCode: \'TARGET-MANAGE-PAGE-MENU\',\n            vue: _frame.ModuleRender,\n            data: _targetManagePage2.default\n        }]\n    }]\n}, {\n    "name": "拓扑图",\n    authorityCode: \'AMP-TOPO-MENU\',\n\n    "path": "topo",\n    vue: _main2.default,\n    data: {\n        btnAuthorityCode: \'AMP-TOPO-LIST-MENU\',\n        authorityCode: [{\n            api: \'/snc-amp/alarm/getPage\',\n            code: \'AMP_ALARM_INFO_GET_PAGE\'\n        }]\n    }\n}];',
        _name: 'C:\\app\\web_amp\\node_modules\\babel-loader\\lib\\index.js!C:\\app\\web_amp\\src\\data\\menu.js',
        _sourceMap:
    { version: 3,
        sources: [Array],
        names: [Array],
        mappings: ';;;;;;AAAA;;AACA;;;;AACA;;;;AACA;;;;AACA;;AAEA;;;;AACA;;;;AACA;;;;AACA;;;;AACA;;;;AACA;;;;AACA;;;;AACA;;;;AACA;;;;AACA;;;;AACA;;;;AAEA;;;;AAEA;;;;;;kBAEe,CACX;AACI,YAAQ,IADZ;AAEIA,mBAAe,wBAFnB;AAGI,YAAQ,6BAHZ;AAIIC,yBAJJ;AAKIC,UAAM,EAACC,QAAO,EAACC,MAAK,MAAN,EAAR;AALV,CADW,EAQX;AACI,YAAQ,MADZ;AAEIJ,mBAAe,kBAFnB;AAGI,YAAQ,wBAHZ;;AAKIK,iBAAY,+BALhB;;AAOIC,qBAAgB,IAPpB;AAQI,gBAAY,CAAC;AACT,gBAAQ,MADC;AAETN,uBAAe,4BAFN;AAGT,gBAAQ,wBAHC;AAITO,cAAM,gCAJG;AAKTN;AALS,KAAD,EAOT;AACC,gBAAQ,MADT;AAECD,uBAAe,kCAFhB;AAGC,gBAAQ,8BAHT;AAICO,cAAM,wBAJP;AAKCN,iCALD;AAMCC,cAAK,CAAC;AACFM,kBAAK,OADH;AAEFR,2BAAe,oCAFb;AAGFE;AAHE,SAAD;AANN,KAPS,EAmBR;AACI,gBAAQ,MADZ;AAEIF,uBAAe,wBAFnB;AAGI,gBAAQ,0BAHZ;AAIIO,cAAM,yBAJV;AAKIN,sCALJ;AAMIC,cAAK;AANT,KAnBQ,EAuCR;AACA,gBAAQ,MADR;AAEAF,uBAAe,yBAFf;AAGAO,cAAM,4BAHN;AAIA,oBAAY,CACR;AACI,oBAAQ,QADZ;AAEIP,2BAAe,+BAFnB;AAGI,oBAAQ,yBAHZ;AAIIC,oCAJJ;AAKIC,kBAAM,iBAAWO;AALrB,SADQ,EASR;AACI,oBAAQ,QADZ;AAEIT,2BAAe,+BAFnB;AAGI,oBAAQ,uBAHZ;AAIIC,oCAJJ;AAKIC,kBAAM,iBAAWQ;AALrB,SATQ,EAgBR;AACI,oBAAQ,MADZ;AAEIV,2BAAe,mCAFnB;AAGI,oBAAQ,uBAHZ;AAIIC,uCAJJ;AAKIC,kBAAK,CACD;AACIM,sBAAK,MADT;AAEIR,+BAAe,uCAFnB;AAGIE,sBAAK,iBAAWS;AAHpB,aADC;AALT,SAhBQ,EAgEL;AACC,oBAAQ,MADT;AAECX,2BAAe,8BAFhB;AAGC,oBAAQ,iBAHT;AAICC,uCAJD;AAKCC,kBAAK,CACD;AACIM,sBAAK,MADT;AAEIR,+BAAe,kCAFnB;AAGIE,sBAAK,iBAAWU;AAHpB,aADC,EAMD;AACIJ,sBAAK,SADT;AAEIR,+BAAe,2CAFnB;AAGIE;AAHJ,aANC,EAWD;AACIM,sBAAK,SADT;AAEIR,+BAAe,gDAFnB;AAGIE;AAHJ,aAXC,EAgBD;AACIM,sBAAK,QADT;AAEIR,+BAAe,wCAFnB;AAGIE;AAHJ,aAhBC,EAqBD;AACIM,sBAAK,SADT;AAEIR,+BAAe,+CAFnB;AAGIE;AAHJ,aArBC,EA0BD;AACIM,sBAAK,KADT;AAEIR,+BAAe,kCAFnB;AAGIE;AAHJ,aA1BC,EA+BD;AACIM,sBAAK,KADT;AAEIR,+BAAe,8CAFnB;AAGIE;AAHJ,aA/BC,EAoCD;AACIM,sBAAK,KADT;AAEIR,+BAAe,sCAFnB;AAGIE;AAHJ,aApCC;AALN,SAhEK,EAgHR;AACI,oBAAQ,MADZ;AAEIF,2BAAe,gCAFnB;AAGI,oBAAQ,kBAHZ;AAIIC,oCAJJ;AAKIC,kBAAM,iBAAWW;AALrB,SAhHQ;AAJZ,KAvCQ,EAoKR;AACIL,cAAM,MADV;AAEIM,cAAM,oBAFV;AAGIC,kBAAU,QAHd;AAIIf,uBAAe,8BAJnB;AAKIC,8BALJ;AAMIM,cAAM,4BANV;AAOIL,cAAM,CAAC;AACH,oBAAQ,KADL;AAEHF,2BAAe,qBAFZ;AAGHC,oCAHG;AAIHC;AAJG,SAAD,EAKJ;AACEM,kBAAM,MADR;AAEER,2BAAe,yBAFjB;AAGEC,oCAHF;AAIEC;AAJF,SALI;AAPV,KApKQ;AARhB,CARW,EAyMX;AACI,YAAQ,KADZ;AAEIF,mBAAe,eAFnB;;AAMI,YAAQ,MANZ;AAOKC,uBAPL;AAQIC,UAAK;AACDc,0BAAiB,oBADhB;AAEDhB,uBAAe,CAqDf;AACIiB,iBAAK,wBADT;AAEIC,kBAAM;AAFV,SArDe;AAFd;AART,CAzMW,C',
        file: 'menu.js',
        sourceRoot: 'C:/app/web_amp',
        sourcesContent: [Array] },
    _originalSource: undefined,
        _innerSourceMap: undefined },
    assets: {},
    built: true,
        _cachedSource:
    { source: ReplaceSource { _source: [Object], _name: undefined, replacements: [Array] },
        hash: 'fdb56ab9021f6cee09a66fb954ccb064' },
    issuer:
        NormalModule {
    dependencies:
        [ [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object] ],
            blocks: [],
        variables: [],
        context: 'C:\\app\\web_amp\\src',
        reasons: [ [Object] ],
        debugId: 1004,
        lastId: null,
        id: './src/main.js',
        portableId: 'node_modules/babel-loader/lib/index.js!src/main.js',
        index: 390,
        index2: 1627,
        depth: 1,
        used: true,
        usedExports: true,
        providedExports: true,
        chunks: [ [Object] ],
        warnings: [],
        dependenciesWarnings: [],
        errors: [],
        dependenciesErrors: [],
        strict: true,
        meta: {},
    request: 'C:\\app\\web_amp\\node_modules\\babel-loader\\lib\\index.js!C:\\app\\web_amp\\src\\main.js',
        userRequest: 'C:\\app\\web_amp\\src\\main.js',
        rawRequest: './src/main.js',
        parser:
    Parser {
        _plugins: [Object],
            options: undefined,
            scope: undefined,
            state: undefined,
            comments: undefined },
    resource: 'C:\\app\\web_amp\\src\\main.js',
        loaders: [ [Object] ],
        fileDependencies: [ 'C:\\app\\web_amp\\src\\main.js' ],
        contextDependencies: [],
        error: null,
        _source:
    SourceMapSource {
        _value: '\'use strict\';\n\nvar _vue = require(\'vue\');\n\nvar _vue2 = _interopRequireDefault(_vue);\n\nvar _vuex = require(\'vuex\');\n\nvar _vuex2 = _interopRequireDefault(_vuex);\n\nvar _vueRouter = require(\'vue-router\');\n\nvar _vueRouter2 = _interopRequireDefault(_vueRouter);\n\nvar _elementUi = require(\'element-ui\');\n\nvar _elementUi2 = _interopRequireDefault(_elementUi);\n\nvar _frame = require(\'@project/frame\');\n\nrequire(\'./config/globalConfig\');\n\nvar _menu = require(\'./data/menu\');\n\nvar _menu2 = _interopRequireDefault(_menu);\n\nfunction _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }\n\n_frame.cacheConfig[\'/snc-amp/api/sysPara/page/getListByParaOrCode\'] = true;\nvar _iteratorNormalCompletion = true;\nvar _didIteratorError = false;\nvar _iteratorError = undefined;\n\ntry {\n    for (var _iterator = _menu2.default[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {\n        var m = _step.value;\n\n        _frame.menu.push(m);\n    }\n} catch (err) {\n    _didIteratorError = true;\n    _iteratorError = err;\n} finally {\n    try {\n        if (!_iteratorNormalCompletion && _iterator.return) {\n            _iterator.return();\n        }\n    } finally {\n        if (_didIteratorError) {\n            throw _iteratorError;\n        }\n    }\n}\n\nvar isProd = process.env.NODE_ENV === \'production\';\n_vue2.default.config.devtools = !isProd;\n_vue2.default.config.silent = isProd;\n_vue2.default.config.productionTip = false;\n\n\n_vue2.default.use(_vueRouter2.default);\n_vue2.default.use(_elementUi2.default);\n_vue2.default.use(_vuex2.default);\n_vue2.default.use(_frame.vuePlugin);\n\nvar router = new _vueRouter2.default({\n    routes: _frame.routes,\n    mode: \'hash\',\n    strict: isProd\n});\n\nvar _store = new _vuex2.default.Store(_frame.store);\n\nwindow.store = _store;\n\nvar app = new _vue2.default({\n    store: _store,\n    router: router,\n    el: \'#app\'\n});',
            _name: 'C:\\app\\web_amp\\node_modules\\babel-loader\\lib\\index.js!C:\\app\\web_amp\\src\\main.js',
            _sourceMap: [Object],
            _originalSource: undefined,
            _innerSourceMap: undefined },
    assets: {},
    built: true,
        _cachedSource: { source: [Object], hash: 'fa274fe22a04cebba829fc7661e27341' },
    issuer:
        MultiModule {
        dependencies: [Array],
            blocks: [],
            variables: [],
            context: 'C:\\app\\web_amp',
            reasons: [],
            debugId: 1000,
            lastId: null,
            id: 1,
            portableId: 'multi webpack-dev-server/client?http://0.0.0.0:8081/ webpack/hot/dev-server webpack-hud babel-polyfill ./src/main.js',
            index: 0,
            index2: 1628,
            depth: 0,
            used: true,
            usedExports: true,
            providedExports: true,
            chunks: [Array],
            warnings: [],
            dependenciesWarnings: [],
            errors: [],
            dependenciesErrors: [],
            strict: false,
            meta: {},
        name: 'app',
            built: true,
            cacheable: true,
            issuer: null,
            useSourceMap: true,
            building: undefined,
            __OccurenceOrderPlugin_occursInEntry: undefined,
            __OccurenceOrderPlugin_occurs: undefined },
    optional: false,
        useSourceMap: true,
        building: undefined,
        buildTimestamp: 1521705005357,
        cacheable: true,
        __OccurenceOrderPlugin_occursInEntry: undefined,
        __OccurenceOrderPlugin_occurs: undefined },
    optional: false,
        useSourceMap: true,
    building: undefined,
    buildTimestamp: 1521705006205,
    cacheable: true,
    __OccurenceOrderPlugin_occursInEntry: undefined,
    __OccurenceOrderPlugin_occurs: undefined }*/
